travis:
  secure:
    BINSTAR_TOKEN: AXgbhhdCXjRAj4kqRoL1NvaMWtcgHINFoJATBC/SwV4Pnr3wv6lOcVAug/1K8N/0bLwEXRIVhZaP+4SHXSO8/PcR4l8+qCOsIyZUPXh4vOYdJhF6vDrjgsXQ+IiDEYF2+hHn4sPJ02RiiJhzTQ9D3cnoxnAnR5a3EtOiNjlVgFd5D81VjJQz3ULQYIvJDjD0fjUfnmymrsx+qBS5+616UEDTVPyPzJ3Tfig07DgtuOXrRtprsKMf8WlBaLfufgmlMq8xY1cnCq3vNaiWzjNrtFBtJ1Fybgum4SW6KFvd+sP196q9dbvlcFfINYR9jZ9EVZbJiGgD2hStzao16XbXAp9cK3PhjsdtklxLHTnm6a1Qn01cATEM5gOKJWMSLmJ5rNEg738u6e1oOPvMfZnq5QfhwZOxJMaql63FsHsnUIitu8OtnVwR0f1Ikfpd87Kr2Qzz+0VrcEpRFrmQ3dxE0htOH7hbustONVEB0g00nVYxCmKBc3i37fBcv1RirZBOEBkO1PF3IhXmWOX0kmPeci8+07Yx+4mD8v5MOqfK08oNpS7q6A+NkWVbmMMBLp/4VwxKwmiVDDX/ISrIbkOdqz4q/VPqKO+sujLoMSNaJ7rMrCreFcJy1DcJpqnSwWn5qkGqlDVkXo9ZBYiJ3Sw8fTloLn5fVfHXjlVtzswF3Q4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
