travis:
  secure:
    BINSTAR_TOKEN: Vl3yhuPSDjGbQh717UxfuKZieuotzyrKXToHj3ils9LyBfhTKEoZVdR5f6By70nT6LzFAIson8hcg7dfBvn+WeI7bQqO8JThDZ05HHCA+7AZ7lU+gjtYrq3ocOwJhdsvCulh9eIGY+a2yXLJsRlN8/7/lf5ImmpfHMtnQ0Jtxu6TQWk9wfAIbS7HJ0tZ+eK61pMN+y/oaImHbJsDH+0qgbPEF7ijMcaSjXubObVSwxD92QRaFfpLHQQ/OrRJH3OuRWdKA3b8fJg7/WgtFyPB4I7eWQ6/RkB61MZUauivBhGc9QjN/zD+l65fvqQVO6W+d867FaDcWhoTz4nyZIcWHpoHLr5h0pNQOmszzXOEnChl0mN2Q75hT0nS2ecKZuwft0D9OOrmGKCrwVeaMb1eSWGmSTkPRWBOAiowekbsO8FSBj8rtbAxK5ILakbbQMiePSv1xhBzsl1LQUDZWFMvc+b09DacFA3kZ5bty6jvsbODqDoQ2Q+sB0cB5S95O6P9QbWroO0Ze3hvB1o7cYyn0gKK8D4heGrs4txdEg8xvCr6gzD2iZZvK+p2Rmp5c5+g7rGFXg2PAUdXpsl4Nb3ymxbhgfVgWPt9yMWibERwAykoxLrEMR6D5Ge3XrszwoNgOEMHHxHJijJl0mLorF2PdlYvkCnBtkPgA2v0yAbc6sk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
